### ISSUE TITLE
Is there a forum thread discussion regarding this project?

### ISSUE THREAD

**Issue by luzpaz** [howie-j/freecad-setup#1]
This looks neat. Is there a discussion somewhere folks can follow ?

**Comment by howie-j** [comment]
Nope, no forum thread. This is just my personal customized freecad setup. [It's sort of based on this](https://github.com/howie-j/FreeCAD-Wizard/blob/main/configurations/howie_simple_mechanical/howie_simple_mechanical.md), but with personal preference customisation regarding shortcuts, toolbars, addons and such.
